### ISSUE TITLE
Error in docker-compose with telegraf config entry

### ISSUE THREAD

**Issue by GarryG** [gcgarner/IOTstack#207]
Hi,

I just tried out IOTstack and it's great ... except for one small problem - I keep getting errors when I try to use telegraf ...

```
root@raspi4:~/IOTstack# docker-compose up -d
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 68, column 5
expected <block end>, but found '<block sequence start>'
  in "./docker-compose.yml", line 75, column 7

```
Line 68 is the first "container_name: telegraf" line right after the "telegraf:" entry. If I move the whole block to somewhere else in the file, the error line moves; removing it lets docker-compose run through successfully, so it's definitely something in the telegraf block.

```
  telegraf:
    container_name: telegraf
    image: telegraf
    volumes:
      - ./services/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
          - cadvisor-arm
          - node-exporter
      - influxdb
      - mosquitto
```

The yaml file is used right out of the generation by menu.sh, nothing was originally edited or changed ...

Sorry, not really learned about yaml files, I reckon it's probably something minor ...

**Comment by Paraphraser** [comment]
Please see [* * THIS PROJECT IS DORMANT * *](https://github.com/gcgarner/IOTstack/issues/194).

It is possible that your problem has been fixed on [SensorsIot/IOTstack](https://github.com/SensorsIot/IOTstack). In any case, you are more likely to get support if you migrate your installation to SensorsIot/IOTstack, find that your problem has not been fixed, and open another issue there.

If you have not already joined [the Discord channel](https://discord.gg/W45tD83), you can often get help there too.

I'd really appreciate it if you would close this issue on gcgarner/IOTstack:

* Recently opened issues give the impression that this repo is active - it isn't.
* A pile of ancient open issues with no responses give the impression that IOTstack has been abandoned - it hasn't been.
* Forking the repo was the only possible way of continuing once Graham Garner "disappeared".

<hr>

I don't use telegraf but I recently ran it up to check something in response to a question on Discord. It just worked and I didn't strike anything like this so my guess is that SensorsIot/IOTstack doesn't have this bug,

**Comment by GarryG** [comment]
> It is possible that your problem has been fixed on [SensorsIot/IOTstack](https://github.com/SensorsIot/IOTstack). In any case, you are more likely to get support if you migrate your installation to SensorsIot/IOTstack, find that your problem has not been fixed, and open another issue there.

Sorry, used a link to this project and didn't actually check out the project page before installing ... Thanks for the pointer. Updated, though still getting the same error ...
